In [ ]:
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib as mpl
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_boston
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
import numpy as np
from statistics import mean 
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
df = pd.read_csv("mRNA_luad_cancer_selected_features_with_stage.txt")
df2 = pd.read_csv("mRNA_luad_normal_selected_features_with_stage.txt")
df3 = pd.concat([df, df2])

In [ ]:
df3.head()

,Unnamed: 0,SAMPLE_ID,TP53,LRP1B,KRAS,PCLO,KEAP1,CDKN2A,CDKN2B,PTPRD,...,MYD88,DNAJB1,TAL2,VHL,RRAS,SUFU,YPEL5,CNBP,CANCER,AJCC_PATHOLOGIC_TUMOR_STAGE
0,1,TCGA-05-4244-01,1.8485,-1.3344,3.3122,-1.1040,0.4341,0.3579,-4.9171,-4.9219,...,-0.6545,0.7177,-0.4452,0.7018,-3.8643,-1.0992,0.0804,-1.6262,1,4.0
1,2,TCGA-05-4249-01,5.1031,-2.1999,7.8642,-2.0559,0.9739,3.9552,-1.1988,-1.2415,...,-0.0951,-1.1713,-2.1687,0.9997,-5.5307,1.8450,0.1412,-1.3173,1,1.0
2,3,TCGA-05-4250-01,-5.6229,-0.0825,7.9838,0.3692,-0.5459,5.6423,-3.8793,-2.9943,...,-0.9910,0.9927,1.0133,0.2920,-2.5057,-0.3163,-0.3269,0.2893,1,3.0
3,4,TCGA-05-4382-01,1.8033,-2.1999,2.2266,-0.2955,-1.3722,5.3724,-1.5561,-1.6959,...,0.6844,-1.9892,0.0170,0.9279,-1.5677,0.7067,-1.6269,-0.4259,1,1.0
4,5,TCGA-05-4384-01,3.8977,2.5339,1.2420,1.0984,1.0324,1.9087,-2.3277,-1.7272,...,-0.8842,-2.9432,-2.1687,1.5310,-4.4192,1.0284,-0.4190,-0.3444,1,3.0

In [ ]:
df3 = df3.drop(columns=['Unnamed: 0'])
df3 = df3.drop(columns= ['SAMPLE_ID'])
df3 = df3.drop(columns= ['AJCC_PATHOLOGIC_TUMOR_STAGE'])
df3 = df3.dropna()
df3

,TP53,LRP1B,KRAS,PCLO,KEAP1,CDKN2A,CDKN2B,PTPRD,FAT4,RELN,...,TLX1,MYD88,DNAJB1,TAL2,VHL,RRAS,SUFU,YPEL5,CNBP,CANCER
0,1.8485,-1.3344,3.3122,-1.1040,0.4341,0.3579,-4.9171,-4.9219,-2.6989,-2.6277,...,1.8694,-0.6545,0.7177,-0.4452,0.7018,-3.8643,-1.0992,0.0804,-1.6262,1
1,5.1031,-2.1999,7.8642,-2.0559,0.9739,3.9552,-1.1988,-1.2415,-1.8269,-2.6135,...,2.3439,-0.0951,-1.1713,-2.1687,0.9997,-5.5307,1.8450,0.1412,-1.3173,1
2,-5.6229,-0.0825,7.9838,0.3692,-0.5459,5.6423,-3.8793,-2.9943,-2.9824,-0.5254,...,2.6991,-0.9910,0.9927,1.0133,0.2920,-2.5057,-0.3163,-0.3269,0.2893,1
3,1.8033,-2.1999,2.2266,-0.2955,-1.3722,5.3724,-1.5561,-1.6959,-2.7915,-0.8632,...,-1.8386,0.6844,-1.9892,0.0170,0.9279,-1.5677,0.7067,-1.6269,-0.4259,1
4,3.8977,2.5339,1.2420,1.0984,1.0324,1.9087,-2.3277,-1.7272,-1.8158,-1.4483,...,-1.8386,-0.8842,-2.9432,-2.1687,1.5310,-4.4192,1.0284,-0.4190,-0.3444,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,-1.7055,-0.9795,3.0884,0.1566,-2.5134,0.6427,1.2772,-0.2089,0.2678,0.1867,...,-1.8386,-1.2103,1.4603,0.2616,0.4191,-0.6057,-1.1035,0.3048,0.1835,0
55,1.4898,-0.1498,-1.5461,1.8521,0.4409,2.4776,-0.7687,-0.2733,0.5229,1.1056,...,-1.8386,-1.7484,-0.3925,-0.5858,0.9276,-2.2235,0.4774,-1.0559,-1.1623,0
56,-0.0292,-0.2268,-0.5561,0.2664,-1.0490,-0.1536,0.2003,-1.0619,-0.4396,-0.2180,...,-1.8386,0.4549,-1.0326,0.8943,1.2562,-0.4371,0.3525,-0.1505,-0.1912,0
57,-0.4686,-0.0549,0.1542,0.4972,0.7642,-1.7234,0.2018,-1.7875,-0.7263,0.1423,...,-1.8386,-0.6622,0.2995,-2.1687,0.0025,0.7528,0.1231,-0.4339,-0.6611,0
58,-1.5036,-0.2341,0.9413,0.2257,-0.7165,-0.4951,0.8008,-0.4135,0.2499,0.2710,...,-1.8386,-1.8142,1.1424,-2.1687,0.3215,0.4433,-0.2094,-0.1747,-0.3630,0

In [ ]:
y = df3['CANCER']
X = df3.loc[:, df3.columns != 'CANCER']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=42)

In [ ]:
X_train.head()

,TP53,LRP1B,KRAS,PCLO,KEAP1,CDKN2A,CDKN2B,PTPRD,FAT4,RELN,...,CRBN,TLX1,MYD88,DNAJB1,TAL2,VHL,RRAS,SUFU,YPEL5,CNBP
287,5.6110,-2.1999,4.5561,2.9708,-1.6919,-1.6390,-3.7721,-2.0037,-2.8587,-1.1603,...,-3.0859,8.0935,-2.9982,-1.6784,-2.1687,0.7882,-5.5451,-0.5116,-2.6573,-2.9821
2,-0.0017,0.3543,-0.1434,-3.5007,1.2647,0.6788,-0.3808,1.3830,0.5451,-0.5304,...,1.5862,-1.8386,1.1826,-0.3801,-2.1687,-2.6167,1.7112,-0.5564,1.8686,1.8477
402,2.9913,0.4513,6.5302,2.4252,-0.6348,4.5943,-2.6161,-1.1581,-0.7941,-0.2330,...,-2.1448,-1.8386,-0.6262,-1.8964,0.6185,1.6636,-4.4556,1.5291,-1.6892,-1.8122
446,3.3685,-1.3453,-0.6843,-0.3883,0.9830,3.8567,-4.5779,-2.3526,-1.8967,-1.5325,...,-1.1957,0.9989,-1.3569,0.0085,0.1362,-0.3468,-0.8085,-0.8592,1.1053,-0.4213
210,3.6553,-1.2312,3.8557,0.5208,0.7645,1.7760,-1.3602,-3.1965,-3.1813,-1.6094,...,-1.2604,-0.7238,-0.1348,-1.4364,0.4172,2.0900,-4.4879,-0.1773,-0.6965,-2.5639

In [ ]:
X_test.head()

,TP53,LRP1B,KRAS,PCLO,KEAP1,CDKN2A,CDKN2B,PTPRD,FAT4,RELN,...,CRBN,TLX1,MYD88,DNAJB1,TAL2,VHL,RRAS,SUFU,YPEL5,CNBP
204,5.7070,-2.1999,9.5395,-1.5564,2.5406,-0.5608,-3.2152,-2.5111,-3.0285,-2.7738,...,-2.3265,3.2527,-0.2226,-0.2157,-1.2905,0.2655,-0.3383,0.9389,-0.7353,-1.1191
70,3.8013,3.7653,1.2455,-0.6528,0.6784,-2.5398,-7.5636,-2.5770,-3.5565,-2.2778,...,-3.7956,-1.8386,-1.2447,0.0099,-2.1687,0.4393,-2.6185,1.9380,-0.6358,-1.6041
131,6.0280,-1.3947,5.3237,1.1384,3.5940,-0.2320,-4.5041,-2.7890,-3.3515,-2.2521,...,-2.3403,1.6676,-1.7223,-1.0480,-2.1687,-0.8621,-4.0626,0.2863,-0.0255,-2.6355
431,1.6126,-1.5778,2.5754,0.1401,-0.1559,1.5302,-2.9536,-4.2890,-3.4265,-2.4958,...,-2.6920,2.5255,0.9350,0.2637,1.7331,2.3249,-3.6949,-0.0907,-2.1827,0.2687
30,-0.4666,-1.2286,0.3012,0.6661,-0.4130,0.0206,0.8410,0.5295,0.9385,0.6449,...,0.1889,-1.8386,0.2270,-0.4573,-0.2344,0.1911,-0.1241,0.3392,-0.4637,-0.1870

In [ ]:
# Scaling

scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
param_grid = {'n_neighbors': np.arange(1, 50)} #np.arange creates sequence of numbers for each k value

grid = GridSearchCV(KNeighborsClassifier(), param_grid=param_grid)

#use meta model methods to fit score and predict model:
grid.fit(X_train_scaled, y_train)

print("best mean cross-validation score: {:.3f}".format(grid.best_score_))
print("best parameters: {}".format(grid.best_params_))
print("test-set score: {:.3f}".format(grid.score(X_test_scaled, y_test)))

best mean cross-validation score: 0.993
best parameters: {'n_neighbors': 46}
test-set score: 0.993

In [ ]:
## Logistic Regression:

#C=100, compare coefs to regular model above.


logreg = LogisticRegression(C=100,multi_class='multinomial').fit(X_train, y_train)





print("Training set score: {:.3f}".format(logreg.score(X_train, y_train)))
print("Test set score: {:.3f}".format(logreg.score(X_test, y_test)))


predicted_vals = logreg.predict(X_test) # y_pred includes your predictions
print("logreg.predict: {}".format(predicted_vals))

Training set score: 1.000
Test set score: 1.000
logreg.predict: [0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1]

In [ ]:
#C=10

logreg = LogisticRegression(C=10).fit(X_train, y_train)


logreg = LogisticRegression(C=10,multi_class='multinomial').fit(X_train, y_train)





print("Training set score: {:.3f}".format(logreg.score(X_train, y_train)))
print("Test set score: {:.3f}".format(logreg.score(X_test, y_test)))


predicted_vals = logreg.predict(X_test) # y_pred includes your predictions
print("logreg.predict: {}".format(predicted_vals))

Training set score: 1.000
Test set score: 1.000
logreg.predict: [0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1]

In [ ]:
#C=1

logreg = LogisticRegression(C=1).fit(X_train, y_train)


logreg = LogisticRegression(C=1,multi_class='multinomial').fit(X_train, y_train)





print("Training set score: {:.3f}".format(logreg.score(X_train, y_train)))
print("Test set score: {:.3f}".format(logreg.score(X_test, y_test)))


predicted_vals = logreg.predict(X_test) # y_pred includes your predictions
print("logreg.predict: {}".format(predicted_vals))

Training set score: 1.000
Test set score: 1.000
logreg.predict: [0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1]

In [ ]:
#C=0.001

logreg = LogisticRegression(C=0.001).fit(X_train, y_train)


logreg = LogisticRegression(C=0.001,multi_class='multinomial').fit(X_train, y_train)





print("Training set score: {:.3f}".format(logreg.score(X_train, y_train)))
print("Test set score: {:.3f}".format(logreg.score(X_test, y_test)))


predicted_vals = logreg.predict(X_test) # y_pred includes your predictions
print("logreg.predict: {}".format(predicted_vals))

Training set score: 0.998
Test set score: 0.993
logreg.predict: [0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1]

In [ ]:
# Linear Regression

lr = LinearRegression()
lr.fit(X_train, y_train)

print("Training set score: {:.3f}".format(lr.score(X_train, y_train)))
print("Test set score: {:.3f}".format(lr.score(X_test, y_test)))

Training set score: 1.000
Test set score: 0.628

### Toby trying logit with L1 penalty, GridSearchCV

C = 1.0 is the best parameter setting

In [ ]:
# Logistic regression with L1 penalty
log_L1_param_grid = {"C": np.logspace(-4, 3, 8)}
log_L1_grid = GridSearchCV(LogisticRegression(penalty = "l1", solver = "liblinear"),
                        log_L1_param_grid)

log_L1_grid.fit(X_train, y_train)

print("Logisitic Regression, L1 penalty, scaled data, GridSearchCV:")
print("Best training set CV score: {:.3f}".format(
    log_L1_grid.best_score_))
print("Best parameters: {}".format(
    log_L1_grid.best_params_))

Logisitic Regression, L1 penalty, scaled data, GridSearchCV:
Best training set CV score: 0.991
Best parameters: {'C': 1.0}

In [ ]:
log_L1 = LogisticRegression(penalty = "l1",  solver='liblinear', C = 1.0)
log_L1.fit(X_train, y_train)

print("Logistic Regression, L1 penalty, C = 1.0, scaled data:")
print("Test set score:\n{:.3f}".format(
    log_L1.score(X_test, y_test)))
print("\n")
print("Logistic Regression, L1 penalty, C = 1.0, KFold CV, scaled data:")
print("Test set CV score:\n{:.3f}".format(
    np.mean(cross_val_score(log_L1, X_test, y_test))))

Logistic Regression, L1 penalty, C = 10.0, scaled data:
Test set score:
1.000


Logistic Regression, L1 penalty, C = 10.0, KFold CV, scaled data:
Test set CV score:
0.979

### Showing the top 15 genes that the model deems most important

In [ ]:
p = pd.DataFrame(log_L1.coef_,
                 index = ["coefficients"], 
                 columns = X.columns).transpose()

p.sort_values(by = 'coefficients', axis = 0, ascending = False).head(15)

        coefficients
ETV4        0.608017
DDX4        0.482399
RAD54L      0.360078
MAGED1      0.237410
RUNX2       0.229043
SSX4        0.204562
RECQL4      0.171240
CBLC        0.166504
PHOX2B      0.161469
DUSP9       0.158902
ALK         0.139778
FGF19       0.126351
DUSP4       0.091257
PDK1        0.080777
NONO        0.062075